version: "3.9"

services:
  nginx:
    image: ghcr.io/edythecow/whmcs-nginx:latest
    restart: unless-stopped
    depends_on:
      - php-fpm
    environment:
      - NGINX_DOMAIN=${DOMAIN}
      - TRAEFIK_SUBNET=${TRAEFIK_SUBNET}
      - PUBLIC_SERVER_IP=${PUBLIC_SERVER_IP}
    volumes:
      - whmcs-www:/var/www
    # אין לייבלים של Traefik כאן. בקוליפיי בחר דומיין והגדר שהשירות מאזין על פורט 80.
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:80/"]
      interval: 30s
      timeout: 5s
      retries: 5

  php-fpm:
    image: ghcr.io/edythecow/whmcs-php-fpm:latest
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - PHP_IDE_CONFIG=xwhmcs
    volumes:
      - whmcs-www:/var/www
    # לייבלים של Ofelia לקרון (לא קשור ל-Traefik)
    labels:
      - "ofelia.enabled=true"
      - "ofelia.job-exec.whmcs.schedule=@every 5m"
      - "ofelia.job-exec.whmcs.command=php -q /var/www/whmcs_storage/crons/cron.php"
      # במידה ותרצה יבוא מיילים לטיקטים כל דקה, הסר הערות:
      # - "ofelia.job-exec.whmcs-mail-import.schedule=@every 1m"
      # - "ofelia.job-exec.whmcs-mail-import.command=php -q /var/www/whmcs_storage/crons/pop.php"
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 5s
      retries: 5

  ofelia:
    image: mcuadros/ofelia:latest
    restart: unless-stopped
    depends_on:
      - php-fpm
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # מומלץ (תואם לקליינטים ישנים יותר, אם צריך):
      - MYSQL_TCP_PORT=3306
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - whmcs-database:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 30s
      timeout: 5s
      retries: 10

volumes:
  whmcs-www:
  whmcs-database:
